#!/usr/bin/env bash
# Run a whole DIRECTORY of claim files through run_claim.sh and assemble one report.
#
# Usage:
#   run_batch.sh <claims-dir> [out-dir] [report-file]
#
# <claims-dir>   directory of claim files (each in the run_claim.sh format:
#                "=== CLAIM ===" / "=== CONTEXT ===" / optional "=== NUMBERS ===").
#                Files are processed in sorted filename order, so prefix them to
#                control sequence, e.g.  B1_ideal_solenoid.txt, B2_neumann_sum.txt.
#                Recognised extensions: .txt .claim .md  (others ignored).
#   [out-dir]    where per-claim run dirs + JSONL land. Default: <claims-dir>/_runs
#   [report-file] assembled Markdown report. Default: <out-dir>/report.md
#
# Each claim fans out to all 5 models in parallel (inside run_claim.sh); the
# claims themselves run SEQUENTIALLY so the OpenRouter rate limit isn't hit by
# 16x5 simultaneous calls. The CLAIM_ID / CLAIM_TITLE for each claim are derived
# from the filename (e.g. "B1_ideal_solenoid.txt" -> ID "B1", title "ideal solenoid"),
# unless the file's first line is a "# Title: ..." comment, which wins.
#
# This driver is shipped with the skill so the orchestration never has to be
# re-generated by hand.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CLAIMS_DIR="${1:?usage: run_batch.sh <claims-dir> [out-dir] [report-file]}"
[ -d "$CLAIMS_DIR" ] || { echo "claims dir not found: $CLAIMS_DIR" >&2; exit 2; }
CLAIMS_DIR="$(cd "$CLAIMS_DIR" && pwd)"

OUT_DIR="${2:-$CLAIMS_DIR/_runs}"
REPORT="${3:-$OUT_DIR/report.md}"
mkdir -p "$OUT_DIR"

# collect claim files in sorted order
shopt -s nullglob
FILES=()
for f in "$CLAIMS_DIR"/*.txt "$CLAIMS_DIR"/*.claim "$CLAIMS_DIR"/*.md; do
  FILES+=("$f")
done
shopt -u nullglob
# sort by basename for stable, predictable order
IFS=$'\n' FILES=($(printf '%s\n' "${FILES[@]}" | sort)); unset IFS

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "no claim files (*.txt/*.claim/*.md) in $CLAIMS_DIR" >&2
  exit 2
fi

echo ">> batch: ${#FILES[@]} claim file(s) from $CLAIMS_DIR" >&2

# report header
{
  printf '# Verification report\n\n'
  printf '_%s claim(s), each independently derived by 5 models then adversarially refuted._\n' "${#FILES[@]}"
} > "$REPORT"

# summary rows accumulate here, flushed into a table at the end
SUMMARY="$OUT_DIR/_summary.tsv"
: > "$SUMMARY"

# derive ID + title for a claim file (echoes "id<TAB>title")
id_title() {  # id_title <file>
  local f="$1" base stem id rest title firstline
  base="$(basename "$f")"; stem="${base%.*}"
  id="${stem%%[_ ]*}"
  rest="${stem#"$id"}"; rest="${rest#[_ ]}"
  title="$(printf '%s' "$rest" | tr '_' ' ')"
  [ -n "$title" ] || title="$stem"
  firstline="$(head -n1 "$f")"
  case "$firstline" in
    "# Title:"*) title="${firstline#\# Title:}"; title="${title# }" ;;
  esac
  printf '%s\t%s' "$id" "$title"
}

# How many claims to run AT ONCE. Each claim itself fans out to 5 models in
# parallel, so MAX_PARALLEL claims = MAX_PARALLEL*5 concurrent OpenRouter calls
# (~MAX_PARALLEL per model). Default 5 → ~25 concurrent, ~5/model — a safe burst.
# or_query.sh backs off on 429/503, so an occasional overshoot self-heals.
MAX_PARALLEL="${MAX_PARALLEL:-5}"
echo ">> running up to $MAX_PARALLEL claim(s) in parallel (5 models each)" >&2

# --- pass 1: launch all claims, gated to MAX_PARALLEL concurrent --------------
# Portable job gate (works on macOS' bash 3.2, where `wait -n` is unavailable):
# keep a list of running PIDs; when it's full, poll until at least one exits.
running_pids=()
gate() {  # block until fewer than MAX_PARALLEL jobs are alive
  while [ "${#running_pids[@]}" -ge "$MAX_PARALLEL" ]; do
    local alive=() p
    for p in "${running_pids[@]}"; do
      kill -0 "$p" 2>/dev/null && alive+=("$p")
    done
    # reassign without tripping `set -u` on an empty array (bash 3.2)
    if [ "${#alive[@]}" -gt 0 ]; then running_pids=("${alive[@]}"); else running_pids=(); fi
    [ "${#running_pids[@]}" -ge "$MAX_PARALLEL" ] && sleep 0.5
  done
}

launched=0
for f in "${FILES[@]}"; do
  launched=$((launched+1))
  stem="$(basename "$f")"; stem="${stem%.*}"
  IFS=$'\t' read -r id title <<<"$(id_title "$f")"
  run_out="$OUT_DIR/$stem"; mkdir -p "$run_out"
  echo ">> [$launched/${#FILES[@]}] launch $id — $title" >&2

  gate
  CLAIM_ID="$id" CLAIM_TITLE="$title" \
    bash "$HERE/run_claim.sh" "$f" "$run_out" >"$run_out/console.log" 2>&1 &
  running_pids+=("$!")
done
wait   # let the final batch finish

# --- pass 2: assemble the report in sorted (stable) order ---------------------
for f in "${FILES[@]}"; do
  stem="$(basename "$f")"; stem="${stem%.*}"
  IFS=$'\t' read -r id title <<<"$(id_title "$f")"
  run_out="$OUT_DIR/$stem"
  frag="$run_out/claim-report.md"
  if [ -f "$frag" ]; then
    printf '\n\n---\n\n' >> "$REPORT"
    cat "$frag" >> "$REPORT"
    headline="$(grep -m1 'models confirm' "$frag" | tr -d '_*' | sed 's/^[[:space:]]*//')"
    printf '%s\t%s\t%s\n' "$id" "$title" "${headline:-(no headline)}" >> "$SUMMARY"
  else
    printf '\n\n---\n\n## %s — %s\n\n> run_claim.sh produced no report (see %s/console.log)\n' \
      "$id" "$title" "$run_out" >> "$REPORT"
    printf '%s\t%s\t%s\n' "$id" "$title" "FAILED — no report" >> "$SUMMARY"
  fi
done

# prepend a summary table right after the intro line
SUMTBL="$OUT_DIR/_summary.md"
{
  printf '\n## Summary\n\n| ID | Claim | Round 2 |\n|---|---|---|\n'
  while IFS=$'\t' read -r id title head; do
    printf '| %s | %s | %s |\n' "$id" "$title" "$head"
  done < "$SUMMARY"
} > "$SUMTBL"

# splice: header (first 3 lines) + summary + the rest of the report body
BODY="$OUT_DIR/_body.md"
tail -n +4 "$REPORT" > "$BODY" 2>/dev/null || : > "$BODY"
{ head -n 3 "$REPORT"; cat "$SUMTBL"; cat "$BODY"; } > "$REPORT.tmp" && mv "$REPORT.tmp" "$REPORT"

echo "" >&2
echo ">> done. raw report: $REPORT" >&2
echo ">> per-claim runs + raw JSONL under: $OUT_DIR/" >&2

# --- pass 3: human-readable synthesis ----------------------------------------
# Turn the raw report into the final 🔴/🟡/🟢 review with exact main.tex:<line>
# references. The paper .tex is taken from $PAPER_TEX if set, otherwise we try to
# locate it automatically so the review is produced without any extra flag.
# Failure here never loses the raw report.

# detect_paper_tex: echo the path to the paper .tex, or nothing.
# Search order: explicit $PAPER_TEX → a `.paper_path` recorded next to the claims
# (the location is known from the very start, when the claims were extracted from
# the paper — write it there in Phase A) → main.tex in $PWD or the report's repo →
# a *single* obvious .tex there. Never guesses when it would be ambiguous.
detect_paper_tex() {
  # 1. explicit override always wins
  if [ -n "${PAPER_TEX:-}" ]; then printf '%s' "$PAPER_TEX"; return; fi

  # 1a. the path recorded at decomposition time, alongside the claims. This is the
  #     authoritative source: the paper's location is known from the start, so
  #     Phase A can drop it in `<claims-dir>/.paper_path` and it survives even when
  #     the claims live far from the paper (e.g. claims in /tmp, paper in a repo).
  local pp="$CLAIMS_DIR/.paper_path"
  if [ -f "$pp" ]; then
    local recorded; recorded="$(head -n1 "$pp" | tr -d '[:space:]')"
    [ -n "$recorded" ] && [ -f "$recorded" ] && { printf '%s' "$recorded"; return; }
  fi

  # candidate roots: where the user invoked us, and the report's own directory
  local report_dir; report_dir="$(cd "$(dirname "$REPORT")" 2>/dev/null && pwd)"
  local roots=("$PWD" "$report_dir" "$report_dir/.." )

  # 1b. a conventional main.tex in any candidate root
  local r
  for r in "${roots[@]}"; do
    [ -n "$r" ] && [ -f "$r/main.tex" ] && { printf '%s' "$r/main.tex"; return; }
  done

  # 2. exactly one .tex in $PWD → take it; if several, pick the largest ONLY when
  #    it is clearly the biggest (>1.5x the runner-up), else stay silent.
  local texs=()
  shopt -s nullglob; texs=("$PWD"/*.tex); shopt -u nullglob
  if [ "${#texs[@]}" -eq 1 ]; then printf '%s' "${texs[0]}"; return; fi
  if [ "${#texs[@]}" -gt 1 ]; then
    local big big_sz second_sz t sz
    big=""; big_sz=0; second_sz=0
    for t in "${texs[@]}"; do
      sz="$(wc -c < "$t" 2>/dev/null | tr -d ' ')"; sz="${sz:-0}"
      if [ "$sz" -gt "$big_sz" ]; then second_sz="$big_sz"; big_sz="$sz"; big="$t"
      elif [ "$sz" -gt "$second_sz" ]; then second_sz="$sz"; fi
    done
    # clearly-largest test: big > 1.5 * runner-up
    if [ "$big_sz" -gt "$(( second_sz * 3 / 2 ))" ]; then printf '%s' "$big"; return; fi
  fi
  # ambiguous or none → echo nothing
}

TEX_PATH="$(detect_paper_tex)"
if [ -n "$TEX_PATH" ] && [ -f "$TEX_PATH" ]; then
  [ -n "${PAPER_TEX:-}" ] || echo ">> auto-detected paper: $TEX_PATH (override with PAPER_TEX=...)" >&2
  bash "$HERE/synthesize_report.sh" "$REPORT" "$TEX_PATH" || \
    echo ">> (synthesis step failed — raw report above is still valid)" >&2
elif [ -n "${PAPER_TEX:-}" ]; then
  echo ">> PAPER_TEX set but not found: $PAPER_TEX — skipping synthesis" >&2
else
  echo ">> no paper .tex found automatically — set PAPER_TEX=/path/to/main.tex for the human review" >&2
fi
